name: pokedex
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.7
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.3.1
  sizer: ^2.0.15
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.7.0
  simple_shadow: ^0.3.1
  expandable_page_view: ^1.0.17
  collection: ^1.18.0
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.13.1
  freezed_annotation: ^2.4.1
  dio: ^5.4.3+1
  infinite_scroll_pagination: ^4.0.0
  widgetbook_annotation: ^3.0.0
  widgetbook: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  flutter_native_splash: ^2.3.13
  freezed: ^2.4.7
  widgetbook_generator: ^3.0.0
flutter:

  assets:
    - assets/images/
    - assets/types/

  uses-material-design: true