name: pokedex
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  go_router: ^14.6.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^8.0.2
  sizer: ^3.0.5
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.7.0
  simple_shadow: ^0.3.1
  expandable_page_view: ^1.0.17
  collection: ^1.18.0
  uuid: ^4.4.0
  freezed_annotation: ^2.4.1
  dio: ^5.4.3+1
  infinite_scroll_pagination: ^4.0.0
  widgetbook_annotation: ^3.0.0
  widgetbook: ^3.0.0
  equatable: ^2.0.7
  flutter_phoenix: ^1.1.1
  auto_size_text: ^3.0.0
  contentsize_tabbarview: ^0.0.2
  translator: ^1.0.3+1
  flutter_radar_chart: ^0.2.1
  deep_pick: ^1.1.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5
  flutter_native_splash: ^2.3.13
  freezed: ^2.4.7
  widgetbook_generator: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  assets:
    - assets/images/
    - assets/types/
    - assets/sounds/

  uses-material-design: true

flutter_icons:
  android: true  
  ios: true
  image_path: "assets/images/pikachu.png"
  daptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/pikachu.png"